rustfmt is already installed by default by rustup

diff --git a/packages/rustfmt/package.yaml b/packages/rustfmt/package.yaml
--- a/packages/rustfmt/package.yaml
+++ b/packages/rustfmt/package.yaml
@@ -13,9 +13,7 @@ categories:
 source:
   id: pkg:generic/rustfmt@x
   build:
-    run: |
-      rustup component add rustfmt
-      cp $(which rustfmt) .
+    run: cp $(which rustfmt) . || echo "rustfmt not found"
     bin: rustfmt
 
 bin:
